### ISSUE TITLE
logstash wiki tracking

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#375]
Use this checklist to track logstash wiki and documentation

- [ ] Update HELK overview picture
  - [ ] remove alien vault logo
  - [ ] update with new indexes #256 
- [ ] document catch all for windows
- [ ] document indexme catch all
- [ ] some general guideline on X amount of devices and or X amount of EPS and or X amount of storage - scenarios
- [ ] how to add custom configurations
- [ ] ECS and what not issues until there is an option in HELK to use ECS or OSSEM (if ever ;) )

**Comment by Cyb3rWard0g** [comment]
Hey @neu5ron , whenever you have some time would you helping with some numbers for `some general guideline on X amount of devices and or X amount of EPS and or X amount of storage - scenarios`? Thank you in advance brother. The rest I believe should be easier to address. Oh also the ECS conversations too would be great to address or have a conversation whenever there is time :)

**Comment by neu5ron** [comment]
@Cyb3rWard0g I think the ECS thing may best be described in a Video/recording.. I dont think I can articulate on keyboard the proper explanation required without spending 2 weeks...
What do you think?
